package com.bookstore.voucher.service;
import com.bookstore.voucher.dto.VoucherRequest;
import com.bookstore.voucher.entity.Voucher;
import com.bookstore.voucher.repository.VoucherRepository;
import java.math.*; import java.time.*; import java.util.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class VoucherService {
 private final VoucherRepository voucherRepository; public VoucherService(VoucherRepository voucherRepository){this.voucherRepository=voucherRepository;}
 public List<Voucher> all(){return voucherRepository.findAll();}
 public Voucher create(VoucherRequest request){ if(voucherRepository.findByCodeIgnoreCase(request.code().trim()).isPresent()) throw new IllegalArgumentException("Mã voucher đã tồn tại"); return save(new Voucher(),request); }
 public Voucher update(Long id,VoucherRequest request){return save(voucherRepository.findById(id).orElseThrow(),request);}
 public void delete(Long id){voucherRepository.deleteById(id);}
 private Voucher save(Voucher voucher,VoucherRequest request){String discountType=request.discountType().trim().toUpperCase(); if(!discountType.equals("PERCENTAGE")&&!discountType.equals("FIXED")) throw new IllegalArgumentException("Loại giảm giá không hợp lệ"); if(discountType.equals("PERCENTAGE")&&request.discountValue().compareTo(new BigDecimal("100"))>0) throw new IllegalArgumentException("Phần trăm giảm tối đa là 100"); voucher.setCode(request.code().trim().toUpperCase()); voucher.setDiscountType(discountType); voucher.setDiscountValue(request.discountValue()); voucher.setMinOrderAmount(request.minOrderAmount()); voucher.setExpiresAt(request.expiresAt()); voucher.setUsageLimit(request.usageLimit()); if(request.active()!=null)voucher.setActive(request.active()); voucher.touch(); return voucherRepository.save(voucher);}
 public BigDecimal preview(String code, BigDecimal subtotal){ if(code==null||code.isBlank()) return BigDecimal.ZERO; Voucher voucher=voucherRepository.findByCodeIgnoreCase(code.trim().toUpperCase()).orElseThrow(()->new IllegalArgumentException("Mã giảm giá không hợp lệ hoặc đã hết hạn")); validate(voucher,subtotal); BigDecimal discountAmount=voucher.getDiscountType().equals("PERCENTAGE")?subtotal.multiply(voucher.getDiscountValue()).divide(new BigDecimal("100"),2,RoundingMode.HALF_UP):voucher.getDiscountValue(); return discountAmount.min(subtotal).setScale(0,RoundingMode.HALF_UP); }
 @Transactional public BigDecimal apply(String code, BigDecimal subtotal){if(code==null||code.isBlank())return BigDecimal.ZERO; Voucher voucher=voucherRepository.findByCodeForUpdate(code.trim().toUpperCase()).orElseThrow(()->new IllegalArgumentException("Mã giảm giá không hợp lệ hoặc đã hết hạn")); validate(voucher,subtotal); voucher.setUsedCount(voucher.getUsedCount()+1); voucherRepository.save(voucher); BigDecimal discountAmount=voucher.getDiscountType().equals("PERCENTAGE")?subtotal.multiply(voucher.getDiscountValue()).divide(new BigDecimal("100"),2,RoundingMode.HALF_UP):voucher.getDiscountValue(); return discountAmount.min(subtotal).setScale(0,RoundingMode.HALF_UP); }
 private void validate(Voucher voucher,BigDecimal subtotal){if(!Boolean.TRUE.equals(voucher.getActive())||(voucher.getExpiresAt()!=null&&voucher.getExpiresAt().isBefore(LocalDateTime.now()))||(voucher.getUsageLimit()!=null&&voucher.getUsedCount()>=voucher.getUsageLimit())||subtotal.compareTo(voucher.getMinOrderAmount())<0) throw new IllegalArgumentException("Mã giảm giá không hợp lệ, chưa đủ điều kiện hoặc đã hết hạn");}
}