import React, { useEffect, useState } from 'react';
import { Plus, Trash2, Edit2, Ticket } from 'lucide-react';
import { voucherService } from '../../services/voucherService';
import { Voucher, VoucherRequest } from '../../types';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { Select } from '../../components/ui/Select';
import { useToast } from '../../context/ToastContext';
const blank: VoucherRequest = { code: '', discountType: 'PERCENTAGE', discountValue: 10, minOrderAmount: 0, expiresAt: '', usageLimit: null, active: true };
export const AdminVouchersPage: React.FC = () => {
 const [items,setItems]=useState<Voucher[]>([]); const [form,setForm]=useState<VoucherRequest>(blank); const [editing,setEditing]=useState<number|null>(null); const [open,setOpen]=useState(false); const {success,error}=useToast();
 const load=async()=>{try{setItems(await voucherService.getAll());}catch(e){error('Không thể tải voucher.');}}; useEffect(()=>{load();},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault(); try{const payload={...form,code:form.code.trim().toUpperCase(),discountValue:Number(form.discountValue),minOrderAmount:Number(form.minOrderAmount),usageLimit:form.usageLimit?Number(form.usageLimit):null,expiresAt:form.expiresAt||undefined}; if(editing) await voucherService.update(editing,payload); else await voucherService.create(payload); success(editing?'Đã cập nhật voucher.':'Đã tạo voucher.'); setOpen(false);setEditing(null);setForm(blank);load();}catch(e:any){error(e.response?.data?.message||'Không thể lưu voucher.');}};
 const edit=(v:Voucher)=>{setEditing(v.id);setForm({code:v.code,discountType:v.discountType,discountValue:Number(v.discountValue),minOrderAmount:Number(v.minOrderAmount),expiresAt:v.expiresAt?.slice(0,16)||'',usageLimit:v.usageLimit??null,active:v.active});setOpen(true);};
 const remove=async(id:number)=>{if(!confirm('Xóa voucher này?'))return;try{await voucherService.delete(id);success('Đã xóa voucher.');load();}catch(e:any){error(e.response?.data?.message||'Không thể xóa voucher.');}};
 return <div style={{display:'flex',flexDirection:'column',gap:'1.5rem'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h1>Quản lý voucher</h1><p style={{color:'var(--text-muted)'}}>Tạo và quản lý mã giảm giá cho khách hàng.</p></div><Button onClick={()=>{setEditing(null);setForm(blank);setOpen(true);}} leftIcon={<Plus size={16}/>}>Tạo voucher</Button></div>{open&&<form onSubmit={submit} className="card" style={{padding:'1.5rem',display:'grid',gap:'1rem',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))'}}><Input label="Mã voucher" value={form.code} onChange={e=>setForm({...form,code:e.target.value})} required/><Select label="Loại giảm" value={form.discountType} onChange={e=>setForm({...form,discountType:e.target.value as any})} options={[{value:'PERCENTAGE',label:'Phần trăm (%)'},{value:'FIXED',label:'Số tiền (₫)'}]}/><Input label="Giá trị giảm" type="number" min="1" value={form.discountValue} onChange={e=>setForm({...form,discountValue:Number(e.target.value)})} required/><Input label="Đơn tối thiểu" type="number" min="0" value={form.minOrderAmount} onChange={e=>setForm({...form,minOrderAmount:Number(e.target.value)})}/><Input label="Hạn sử dụng" type="datetime-local" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})}/><Input label="Lượt dùng tối đa" type="number" min="1" value={form.usageLimit??''} onChange={e=>setForm({...form,usageLimit:e.target.value?Number(e.target.value):null})}/><label style={{display:'flex',alignItems:'center',gap:8}}><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Đang hoạt động</label><div style={{gridColumn:'1/-1',display:'flex',gap:8}}><Button type="submit">Lưu</Button><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Hủy</Button></div></form>}<div className="card table-container"><table className="table"><thead><tr><th>Mã</th><th>Giảm</th><th>Đơn tối thiểu</th><th>Sử dụng</th><th>Trạng thái</th><th></th></tr></thead><tbody>{items.map(v=><tr key={v.id}><td><strong><Ticket size={15}/> {v.code}</strong></td><td>{v.discountType==='PERCENTAGE'?`${v.discountValue}%`:`${Number(v.discountValue).toLocaleString('vi-VN')} ₫`}</td><td>{Number(v.minOrderAmount).toLocaleString('vi-VN')} ₫</td><td>{v.usedCount}{v.usageLimit?` / ${v.usageLimit}`:''}</td><td>{v.active?'Đang bật':'Đã tắt'}</td><td><Button size="sm" variant="ghost" onClick={()=>edit(v)}><Edit2 size={15}/></Button><Button size="sm" variant="ghost" onClick={()=>remove(v.id)}><Trash2 size={15}/></Button></td></tr>)}</tbody></table>{items.length===0&&<p style={{padding:'1rem',color:'var(--text-muted)'}}>Chưa có voucher.</p>}</div></div>;
};